name: ci

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install gnat
      run: sudo apt-get install -y gnat
    - name: Install llvm
      run: sudo apt-get install -y llvm
    - uses: actions/checkout@v2
    - uses: mishas/setup-bazelisk-action@v1
    - name: Mount bazel cache  # Optional
      uses: actions/cache@v1
      with:
        path: "~/.cache/bazel"
        key: bazel
    - run: bazelisk run //example:example
